[package]
name = "snowglobe"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
glam = "0.29.0"
glow = "0.14.0"
image = "0.25.2"
rapier2d = "0.22.0"
sdl3-sys = "0.0.9"
